name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/.pnpm-store
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        mkdir -p ${{ github.workspace }}/.pnpm-store
        pnpm config set store-dir ${{ github.workspace }}/.pnpm-store
        pnpm install --no-frozen-lockfile

    - name: Run build
      run: pnpm build

    - name: Run lint
      run: pnpm lint